# Generated by Django 4.2.1 on 2023-05-26 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=5, unique=True, validators=[
                    django.core.validators.RegexValidator(regex='^[0-9]{4}[A-Z]$')])),
                ('capacity', models.PositiveIntegerField(default=1,
                                                         validators=[django.core.validators.MinValueValidator(1),
                                                                     django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1,
                                                       validators=[django.core.validators.MinValueValidator(1),
                                                                   django.core.validators.MaxValueValidator(1000)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='CargoCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.car')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.cargo')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='cars',
            field=models.ManyToManyField(through='cargo_app.CargoCar', to='cargo_app.car'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cargos',
                                    to='cargo_app.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pick_up_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_cargos',
                                    to='cargo_app.location'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars',
                                    to='cargo_app.location'),
        ),
    ]
