# Generated by Django 4.2.1 on 2023-05-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_location_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
    ]
